### PR TITLE
fix MSC-related problems

### PR DESCRIPTION
**Pull request by cwehmeyer**

### CODE REVIEW

**Comment by marscher** [comment]
the linking issue also appears in pyemma on osx

**Comment by cwehmeyer** [comment]
PY35 only?

**Comment by marscher** [comment]
On 18.02.2017 13:32, Christoph Wehmeyer wrote:
> PY35 only?
no its py27 there, but not 35...

**Comment by cwehmeyer** [comment]
Strange. Here, PY27 works fine.

**Comment by marscher** [comment]
https://github.com/omnia-md/conda-recipes/pull/477 last comment

**Comment by marscher** [comment]
this still didn't succeed?

**Comment by cwehmeyer** [comment]
this worked

**Comment by marscher** [comment]
For pyemma the flag didn' help, I'm currently trying the other suggested flag...

**Pull request merged**
