### PR TITLE
[appveyor] prefix visual cpp env

### LINKED ISSUE #28: build fails on windows
On appveyor, thermotools does not build correctly for `Environment: PYTHON=C:\Miniconda3-x64, CONDA_PY=34, ARCH=64, CONDA_NPY=110`:

```
Build started
git clone -q --branch=devel https://github.com/markovmodel/thermotools.git C:\projects\thermotools
git checkout -qf b166d8681246e39685b3c79035a902a747d2eff0
Running Install scripts
SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%;
conda config --set always_yes true
conda config --add channels omnia
conda install -q conda-build
Fetching package metadata: ...... 
Solving package specifications: . 
Package plan for installation in environment C:\Miniconda3-x64:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    msvc_runtime-1.0.1         |           vc10_0         1.1 MB
    patch-2.5.9                |                1          56 KB
    conda-env-2.4.4            |           py34_2          51 KB
    markupsafe-0.23            |           py34_0          24 KB
    psutil-3.2.2               |           py34_0         106 KB
    pyyaml-3.11                |           py34_2         117 KB
    requests-2.8.1             |           py34_0         646 KB
    setuptools-18.5            |           py34_0         652 KB
    wheel-0.26.0               |           py34_1         118 KB
    conda-3.18.6               |           py34_0         223 KB
    jinja2-2.8                 |           py34_0         299 KB
    pip-7.1.2                  |           py34_0         1.5 MB
    conda-build-1.18.2         |           py34_0         294 KB
    ------------------------------------------------------------
                                           Total:         5.1 MB

The following NEW packages will be INSTALLED:

    conda-build:  1.18.2-py34_0
    jinja2:       2.8-py34_0   
    markupsafe:   0.23-py34_0  
    msvc_runtime: 1.0.1-vc10_0  [vc10]
    patch:        2.5.9-1      
    pip:          7.1.2-py34_0 
    psutil:       3.2.2-py34_0 
    setuptools:   18.5-py34_0  
    wheel:        0.26.0-py34_1

The following packages will be UPDATED:

    conda:        3.16.0-py34_0 --> 3.18.6-py34_0
    conda-env:    2.4.2-py34_0  --> 2.4.4-py34_2 
    pyyaml:       3.11-py34_1   --> 3.11-py34_2  
    requests:     2.7.0-py34_0  --> 2.8.1-py34_0 

conda build -q conda-recipe
Removing old build environment
Removing old work directory
BUILD START: thermotools-dev-np110py34_0
Fetching package metadata: ........ 
Solving package specifications: .................. 
C:\Miniconda3-x64\conda-bld\work>call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat" amd64 
The specified configuration type is missing.  The tools for the
configuration might not be installed.

C:\Miniconda3-x64\conda-bld\work>set INCLUDE=C:\Miniconda3-x64\envs\_build\Library\include; 

C:\Miniconda3-x64\conda-bld\work>set LIB=C:\Miniconda3-x64\envs\_build\Library\lib; 

C:\Miniconda3-x64\conda-bld\work>REM ===== end generated header ===== 

C:\Miniconda3-x64\conda-bld\work>"C:\Miniconda3-x64\envs\_build\python.exe" setup.py install 
running install
Compiling ext/bar/bar.pyx because it changed.
Compiling ext/wham/wham.pyx because it changed.
Compiling ext/mbar/mbar.pyx because it changed.
Compiling ext/dtram/dtram.pyx because it changed.
Compiling ext/util/util.pyx because it changed.
[1/5] Cythonizing ext/bar/bar.pyx
[2/5] Cythonizing ext/dtram/dtram.pyx
[3/5] Cythonizing ext/mbar/mbar.pyx
[4/5] Cythonizing ext/util/util.pyx
[5/5] Cythonizing ext/wham/wham.pyx
running bdist_egg
running egg_info
creating thermotools.egg-info
writing top-level names to thermotools.egg-info\top_level.txt
writing dependency_links to thermotools.egg-info\dependency_links.txt
writing requirements to thermotools.egg-info\requires.txt
writing thermotools.egg-info\PKG-INFO
writing manifest file 'thermotools.egg-info\SOURCES.txt'
reading manifest file 'thermotools.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'thermotools.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build
creating build\lib.win-amd64-3.4
creating build\lib.win-amd64-3.4\thermotools
copying thermotools\callback.py -> build\lib.win-amd64-3.4\thermotools
copying thermotools\_version.py -> build\lib.win-amd64-3.4\thermotools
copying thermotools\__init__.py -> build\lib.win-amd64-3.4\thermotools
running build_ext
building 'thermotools.bar' extension
Traceback (most recent call last):
  File "setup.py", line 140, in <module>
    scripts=[]
  File "C:\Miniconda3-x64\envs\_build\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Miniconda3-x64\envs\_build\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Miniconda3-x64\envs\_build\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Miniconda3-x64\envs\_build\lib\site-packages\setuptools-18.5-py3.4.egg\setuptools\command\install.py", line 67, in run
  File "C:\Miniconda3-x64\envs\_build\lib\site-packages\setuptools-18.5-py3.4.egg\setuptools\command\install.py", line 109, in do_egg_install
  File "C:\Miniconda3-x64\envs\_build\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Miniconda3-x64\envs\_build\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Miniconda3-x64\envs\_build\lib\site-packages\setuptools-18.5-py3.4.egg\setuptools\command\bdist_egg.py", line 160, in run
  File "C:\Miniconda3-x64\envs\_build\lib\site-packages\setuptools-18.5-py3.4.egg\setuptools\command\bdist_egg.py", line 146, in call_command
  File "C:\Miniconda3-x64\envs\_build\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Miniconda3-x64\envs\_build\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Miniconda3-x64\envs\_build\lib\site-packages\setuptools-18.5-py3.4.egg\setuptools\command\install_lib.py", line 10, in run
  File "C:\Miniconda3-x64\envs\_build\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Miniconda3-x64\envs\_build\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Miniconda3-x64\envs\_build\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Miniconda3-x64\envs\_build\lib\site-packages\setuptools-18.5-py3.4.egg\setuptools\command\build_ext.py", line 49, in run
  File "C:\Miniconda3-x64\envs\_build\lib\site-packages\Cython\Distutils\build_ext.py", line 164, in run
    _build_ext.build_ext.run(self)
  File "C:\Miniconda3-x64\envs\_build\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "C:\Miniconda3-x64\envs\_build\lib\site-packages\Cython\Distutils\build_ext.py", line 172, in build_extensions
    self.build_extension(ext)
  File "C:\Miniconda3-x64\envs\_build\lib\site-packages\setuptools-18.5-py3.4.egg\setuptools\command\build_ext.py", line 174, in build_extension
  File "C:\Miniconda3-x64\envs\_build\lib\distutils\command\build_ext.py", line 503, in build_extension
    depends=ext.depends)
  File "C:\Miniconda3-x64\envs\_build\lib\distutils\msvc9compiler.py", line 460, in compile
    self.initialize()
  File "C:\Miniconda3-x64\envs\_build\lib\distutils\msvc9compiler.py", line 371, in initialize
    vc_env = query_vcvarsall(VERSION, plat_spec)
  File "C:\Miniconda3-x64\envs\_build\lib\site-packages\setuptools-18.5-py3.4.egg\setuptools\msvc9_support.py", line 52, in query_vcvarsall
  File "C:\Miniconda3-x64\envs\_build\lib\distutils\msvc9compiler.py", line 287, in query_vcvarsall
    raise ValueError(str(list(result.keys())))
ValueError: ['lib', 'path', 'include']

C:\Miniconda3-x64\conda-bld\work>if errorlevel 1 exit 1 

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    python-3.4.3               |                4        25.9 MB  defaults
    cython-0.23.4              |           py34_0         1.9 MB  defaults
    numpy-1.10.1               |           py34_0        22.6 MB  defaults
    six-1.10.0                 |           py34_0          17 KB  defaults
    scipy-0.16.0               |      np110py34_0        81.6 MB  defaults
    msmtools-1.1               |      np110py34_2         801 KB  omnia
    ------------------------------------------------------------
                                           Total:       132.8 MB

The following NEW packages will be INSTALLED:

    cython:       0.23.4-py34_0      defaults
    msmtools:     1.1-np110py34_2    omnia   
    msvc_runtime: 1.0.1-vc10_0       defaults [vc10]
    numpy:        1.10.1-py34_0      defaults
    pip:          7.1.2-py34_0       defaults
    python:       3.4.3-4            defaults
    scipy:        0.16.0-np110py34_0 defaults
    setuptools:   18.5-py34_0        defaults
    six:          1.10.0-py34_0      defaults
    wheel:        0.26.0-py34_1      defaults

Removing old work directory
Copying C:\projects\thermotools to C:\Miniconda3-x64\conda-bld\work
Package: thermotools-dev-np110py34_0
source tree in: C:\Miniconda3-x64\conda-bld\work
Command failed: C:\windows\system32\cmd.exe /c call bld.bat
Command exited with code 1
```

### PR DESCRIPTION
**Pull request by marscher**
Fixes #28

### CODE REVIEW

**Comment by cwehmeyer** [comment]
Thanks!

In the future, please make only PR into the devel branch.

**Comment by marscher** [comment]
So what is the purpose of the master branch then?

**Comment by marscher** [comment]
Please set devel as default branch then to avoid confusion.

**Comment by cwehmeyer** [comment]
The master branch should always point to the latest release.

**Comment by cwehmeyer** [comment]
devel is now the default branch

**Pull request merged**
